BUK2on_on/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buk2on_on/', include('recommends.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('create_account/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

recommends/urls.py
from django.urls import path
from . import views

app_name = 'buk2on_on'
urlpatterns = [
    path('', views.index , name='index'),
    path('<int:restaurant_pk>/', views.detail , name='detail'),
    path('create/', views.create, name = 'create'),
    path('<int:restaurant_pk>/update/', views.update, name = 'update'),
    path('<int:restaurant_pk>/delete/', views.delete, name = 'delete'),
    path('seoul/', views.seoul_main , name = 'seoul_main'),
    path('busan/', views.busan_main , name = 'busan_main'),
    path('etc/', views.etc_main , name = 'etc_main'),
    path('<int:restaurant_pk>/comments/', views.comments_create , name = 'comments_create'),
] 

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    email = models.EmailField(
    blank = True,
    verbose_name='email',
    max_length=255,
    unique=True,
    )
    
    profile_pic = ProcessedImageField(
    		blank = True,
        	upload_to = 'profile/images',
        	processors = [ResizeToFill(300, 300)],
        	format = 'JPEG',
        	options = {'quality':90},
    		)


    date_of_birth = models.DateField(blank = True,null=True )
    instagram_url = models.CharField(max_length=255,null=True, blank=True,)
    twitter_url = models.CharField(max_length=255,null=True, blank=True,)
    facebook_url = models.CharField(max_length=255,null=True, blank=True,)
    youtube_url = models.CharField(max_length=255,null=True, blank=True,)


    

recommends/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Restaurant(models.Model):
    province = (('1','Seoul'),('2','Busan'),('3','etc.'))
    region = models.CharField(max_length=20, choices=province)
    name = models.CharField(max_length = 20)
    adress = models.CharField(max_length=50)
    stars = models.IntegerField()
    bestMenu = models.CharField(max_length=100)
    reason = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mainImage = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    

def get_image_filename(instance, filename):
    name = instance.restaurant.name
    slug = slugify(name)
    return "restaurant_images/%s-%s" % (slug, filename)  


class Comment(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Images(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="image")
    image = models.ImageField(blank=False, upload_to=get_image_filename)

    image = ProcessedImageField(
    		blank = True,
            upload_to=get_image_filename,
        	processors = [ResizeToFill(350, 520)],
        	format = 'JPEG',
        	options = {'quality':90},
    		)

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
    def __str__(self):
       return str(self.restaurant)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):

    username = forms.CharField(
        required = True,
        label='ID',
        widget=forms.TextInput(
            attrs={
                'class': 'username',
                'placeholder': 'Required',
                'maxlength': 255,
            }
        ),
        error_messages={
            'required': '아이디를 입력하세요.',
        }
    )

    email = forms.EmailField(
        required = True,
        label='E-mail',
        widget=forms.TextInput(
            attrs={
                'class': 'email',
                'placeholder': 'Required',
                'maxlength': 255,
            }
        ),
        error_messages={
            'required': '이메일을 입력하세요.',
        }
    )

    date_of_birth = forms.DateField(
    required = False,
    label='Date of Birth',
    widget=forms.DateInput(
        attrs={
            'placeholder': 'yy-mm-dd',
            'type' : 'date' ,
            'size': 40,
        }
    ))

    instagram_url = forms.CharField(
    required = False,
    label='Instagram',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))

    twitter_url = forms.CharField(
    required = False,
    label='Twitter',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))
    facebook_url = forms.CharField(
    required = False,
    label='Facebook',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))
    youtube_url = forms.CharField(
    required = False,
    label='Youtube',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))


    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email','date_of_birth','instagram_url','twitter_url','facebook_url','youtube_url','profile_pic')



class CustomUserChangeForm(forms.ModelForm):

    email = forms.EmailField(
        required = True,
        label='E-mail',
        widget=forms.TextInput(
            attrs={
                'class': 'email',
                'placeholder': 'Required',
                'maxlength': 255,
            }
        ),
        error_messages={
            'required': '이메일을 입력하세요.',
        }
    )

    date_of_birth = forms.DateField(
    required = False,
    label='Date of Birth',
    widget=forms.DateInput(
        attrs={
            'placeholder': 'yy-mm-dd',
            'type' : 'date' ,
            'size': 40,
        }
    ))

    instagram_url = forms.CharField(
    required = False,
    label='Instagram',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))

    twitter_url = forms.CharField(
    required = False,
    label='Twitter',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))
    facebook_url = forms.CharField(
    required = False,
    label='Facebook',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))
    youtube_url = forms.CharField(
    required = False,
    label='Youtube',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'option',
            'maxlength': 255,
            'size': 40,

        }
    ))



    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email','date_of_birth','instagram_url','twitter_url','facebook_url','youtube_url','profile_pic')

accounts/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.http import JsonResponse



def login(request):
    if request.user.is_authenticated:
        return redirect('buk2on_on:index')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('buk2on_on:index')
    else :

        messages.error(request, 'Please correct the error below.')
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('buk2on_on:index')


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    print(person.restaurant_set.count())
    if person.restaurant_set.count() >= 10 :
        recentlyUpdate = True
    else :
        recentlyUpdate = False

    context = {
            'person' : person,
            'recentlyUpdate': recentlyUpdate
        }
    return render(request, 'accounts/profile.html',context)


def signup(request):
    if request.method == 'POST':
        signup_form = CustomUserCreationForm(request.POST, request.FILES)
        if signup_form.is_valid():
            user = signup_form.save()
            # Profile.objects.create(user=user) #프로필 생성
            auth_login(request, user)
            return redirect('accounts:profile' , user.username )
    
    else:
        signup_form = CustomUserCreationForm()

    context = {
        'signup_form' : signup_form,
    }
    
    return render(request,'accounts/signup.html', context)


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        password_form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:profile' , user.username )

    
    else:
        form = CustomUserChangeForm(instance=request.user)

    context = {
        'form' : form,
    }
    
    return render(request,'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, password_form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:profile' , user.username )
        else :
            messages.error(request, 'Please correct the error below.')

    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form' : password_form,
    }
    
    return render(request,'accounts/change_password.html', context)


def follow(request, user_pk):
    print('hello')
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed' : is_followed,
            'followers_count' : person.followers.count(),
            'followings_count' : person.followings.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin:12rem;">

  <div class="container">
    <h1 class='section_title'>password change</h1>
    {% if error_message %}<p stlye='color:yellowgreen;'><strong>{{ error_message }}</strong></p>{% endif %}
    <form action= "{% url 'accounts:change_password' %}" method="POST" enctype ="multipart/form-data">
      {% csrf_token %}
      {{ password_form.as_p }}
      <input type="submit">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin:12rem;">


  <div class="container">
    <h1 class='section_title'>LOGIN</h1>
    <div style="margin:2rem;">

    <form action="#" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value='login' type="button" class="btn btn-outline-secondary">
    </form>
    <div style="margin:2rem;">
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin:8rem;">
  <div class="container" >
    <h1 class='section_title' style="margin-top:1rem;">PROFILE</h1>
    <div style='display: flex;'>
      
      <div style="justify-content: center; align-items: center; align-self: center; ">
        {% if person.profile_pic %}
            <img src="{{person.profile_pic.url}}" alt="{% static 'default_avatar2.jpg' %}"  width="150" height="150" style="border-radius : 70%; overflow:hidden; margin-right:5rem;">
        {% else %}
            <img src=" {% static 'default_avatar2.jpg' %} " alt="no image"  width="150" height="150" style="border-radius : 70%; overflow:hidden; margin-right:5rem; ">
        {% endif %}
      </div>


      {% if recentlyUpdate == True  %}
        <i class="fa-sharp fa-solid fa-certificate" style="color:skyblue; margin-right:1rem;"></i>      
      {% else %}
        
      {% endif %}


      <section style='display: flex; flex-direction:column; justify-content:left; align-itmes:left; margin-top:1.3rem;' >
        <div class= "d-flex flex-row justify-content-left  align-itmes-left row-6 " style='margin-bottom:2rem;'>
          <h3 style='margin-right:2rem;'>
              {{person.username|upper}}
          </h3>

          {% if request.user != person %}
          <form id="follow-form" data-user-id="{{person.pk}}" style='display: inline; '>
              {% csrf_token %}
              {% if request.user in person.followers.all %}
              <input type="submit" value="UNFOLLOW" class="btn btn-light btn-sm" >
              {% else %}
              <input type="submit" value="FOLLOW" class="btn btn-outline-light btn-sm">
              {% endif %}
          </form>   
          {% endif %} 
        </div>
        <div class="d-flex flex-row row-6" style="font-size:0.8rem; justify-content:space-round; align-itmes:center;">
          <div class="d-flex row-4 row-md-4" style=" margin-right:2rem; " >
            Following  &nbsp&nbsp <span id="followings-count">{{person.followings.all|length}}</span> &nbsp&nbsp&nbsp&nbsp
          </div>
          <div class="d-flex row-4 row-md-4" style=" margin-right:2rem; ">
            Follower   &nbsp&nbsp <span id="followers-count">{{person.followers.all|length}}</span>&nbsp&nbsp&nbsp&nbsp
          </div>
          <div class="d-flex row-4 row-md-4" style=" margin-right:2rem; ">
            Recommends  &nbsp&nbsp <span>{{person.restaurant_set.all|length}}</span>&nbsp&nbsp&nbsp&nbsp 
          </div>
        </div>
        <div class="d-flex flex-row row-6" style="font-size:0.8rem; justify-content:flex-start; align-itmes:center; margin-top:1rem;">
            {% if person.instagram_url %}
              <div class="d-flex row-6 row-md-6" >Instagram 
                <a href="{{person.instagram_url}}" class="btn_submit" style="background: none; border:none; margin-right:2rem; margin-left:1rem; "><i class="fa-brands fa-instagram fa-xl" style="color:white;"></i></a>
              </div>
            {% endif %}
            {% if person.twitter_url %}
              <div class="d-flex row-6 row-md-6">Twitter 
                <a  href="{{person.twitter_url}}" class="btn_submit" style="background: none; border:none; margin-right:2rem; margin-left:1rem; "><i class="fa-brands fa-twitter fa-xl" style="color:white;"></i></a>
              </div>
            {% endif %}
            {% if person.youtube_url %}
              <div class="d-flex row-6 row-md-6">Youtube 
                <a  href="{{person.youtube_url}}" class="btn_submit" style="background: none; border:none; margin-right:2rem; margin-left:1rem; "><i class="fa-brands fa-youtube fa-xl" style="color:white;"></i></a>
              </div>
            {% endif %}
            {% if person.facebook_url %}
              <div class="d-flex row-6 row-md-6">Facebook 
                <a  href="{{person.facebook_url}}" class="btn_submit" style="background: none; border:none; margin-right:2rem; margin-left:1rem; "><i class="fa-brands fa-facebook fa-xl" style="color:white;"></i></a>
              </div>
            {% endif %}
        </div> 
      </div>
    </section>
    
    
    <div style=" border:1px solid none; height:1.2rem;" ></div>
    <hr>
    <div style=" border:1px solid none; height:1.2rem;" ></div>

    <h3 style="bottom:2rem; display:inline;"><b>{{person.username|upper}} 's </b></h3>
    <h2 style="bottom:2rem; display:inline; font-size:1.3rem;">recommends</h2>
    <div style=" border:1px solid none; height:2rem;" ></div>
  
  
  
    {% for recommend  in person.restaurant_set.all  %}
      {% if recommend.stars == 3 %}
        <div style="margin-bottom:1.3rem; margin-left:100px;">{{recommend.name}}  <span style='margin-left:1rem ;'>★★★</span></div>
        {% comment %} <a href="{% url 'buk2on_on:detail' recommend.pk %}"><div style="margin-bottom:1.3rem; margin-left:100px;">{{recommend.name}}  <span style='margin-left:1rem ;'>★★★</span></div></a> {% endcomment %}
      {% elif recommend.stars == 2 %}
        <div style="margin-bottom:1.3rem; margin-left:100px;">{{recommend.name}}  <span style='margin-left:1rem ;'>★★</span></div>
      {% elif recommend.stars == 1 %}
        <div style="margin-bottom:1.3rem; margin-left:100px;">{{recommend.name}}  <span style='margin-left:1rem ;'>★</span></div>
      {% elif recommend.stars == 0 %}
        <div style="margin-bottom:1.3rem; margin-left:100px;">{{recommend.name}}  <span style='margin-left:1rem ;'>none</span></div>
      {% endif %} 
    {% endfor %}
  
    <div style=" border:1px solid none; height:1.2rem;" ></div>
    {% if request.user == person %}
      <hr>
      <div style=" border:1px solid none; height:1.2rem;" ></div>
      <a href="{% url 'accounts:update' %}" style="color:gray;" class="btn btn-outline-secondary">UPDATE ACCOUNT</a>
      
      <div style=" border:1px solid none; height:1.2rem;" ></div>
      <hr>
      <form action="{% url 'accounts:logout' %}" method = "POST">
          {% csrf_token %}
          <input type="submit" value="LOGOUT"  style="color:white;" class="btn btn-outline-danger">
      </form>
      <hr>
    
    {% endif %}


  </div>


{% endblock content %}


{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#follow-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    form.addEventListener('submit', function(event){
      event.preventDefault()
      const userId = event.target.dataset.userId

      axios({
        method :'post',
        url : `/accounts/${userId}/follow/`,
        headers : {'X-CSRFToken' : csrftoken,}
      })
      .then((response) => {
        const isFollowed = response.data.is_followed
        console.log(isFollowed)

        const followBtn = document.querySelector('#follow-form > input[type=submit]')
        if (isFollowed === true) {
          followBtn.value = 'unfollow'
        } else {
          followBtn.value = 'follow'
        }
        const followersCountTag = document.querySelector('#followers-count')
        const followingsCountTag = document.querySelector('#followings-count')
        const followersCount = response.data.followers_count
        const followingsCount = response.data.followings_count
        followersCountTag.innerText = followersCount
        followingsCountTag.innerText = followingsCount
      })
      .catch((error) => {
        console.log(error.response)
      })
    })



  </script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin:12rem;">

  <div class="container">
    <h1 class='section_title'>Create Account</h1>
    {% if error_message %}<p stlye='color:red;'><strong>{{ error_message }}</strong></p>{% endif %}
    <div style="margin:2rem;">

    <form action= "{% url 'accounts:signup' %}" method="POST" enctype ="multipart/form-data">
      {% csrf_token %}
      {% comment %} {{ signup_form.as_p }} {% endcomment %}
      {% for field in signup_form %}
        <div style="margin-bottom: 1.5rem; margin-left: 1rem;">
        {{ field.label_tag }} 
        <div style="margin-top: 0.2rem;">
        {{ field }} <span>{{ field.errors }} </span></div>
        </div>
      {% endfor %}
      <div style="margin-left:1rem;">
        <input type="submit" value='Sign Up'>
      </div>
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin:12rem;">

  <div class="container">
    <h1 class='section_title'>UPDATE</h1>
    <h3>ID : {{request.user.username}}</h3>
    <div style="margin:2rem;">
    <form action= "{% url 'accounts:update' %}" method="POST" enctype ="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <div style="margin-bottom: 1.5rem; margin-left: 1rem;">
        {{ field.label_tag }} 
        <div style="margin-top: 0.2rem;">
        {{ field }} <span>{{ field.errors }} </span></div>
        </div>
      {% endfor %}
      
      <div style="margin-left:1rem;">
        <input type="submit">
        <div style="margin-top:1rem;">
          <button type="button" name="change_password" onClick="location.href='{% url 'accounts:change_password'%}'">password change</button>
        </div>
      </div>
    </form>
</div>
{% endblock content %}