BUK2on_on/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buk2on_on/', include('recommends.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('create_account/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

recommends/urls.py
from django.urls import path
from . import views

app_name = 'buk2on_on'
urlpatterns = [
    path('', views.index , name='index'),
    path('<int:restaurant_pk>/', views.detail , name='detail'),
    path('create/', views.create, name = 'create'),
    path('<int:restaurant_pk>/update/', views.update, name = 'update'),
    path('<int:restaurant_pk>/delete/', views.delete, name = 'delete'),
    path('seoul/', views.seoul_main , name = 'seoul_main'),
    path('busan/', views.busan_main , name = 'busan_main'),
    path('etc/', views.etc_main , name = 'etc_main'),
    path('<int:restaurant_pk>/comments/', views.comments_create , name = 'comments_create'),
] 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/3c81a506f7.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
  <link rel="icon" href="https://img.danawa.com/prod_img/500000/529/378/img/8378529_1.jpg?shrink=500:500&_v=20190627120247">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&family=Nanum+Pen+Script&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,900;1,700&display=swap" rel="stylesheet">
  <title>BUK2 on&on</title>

  
</head>
<body style="background-color: black ; color:white; box-sizing: border-box; ">

    <div class ="main_nav" >
        <nav class="navbar navbar-dark navbar-expand-lg" style="background: rgba(0, 0, 0, .5); position:fixed;width: 100%; top: 0%;">
            <div class="container-fluid" >
                <a class="navbar-brand" href="{% url 'buk2on_on:index' %}" style="color:white ; font-family:impact ;-webkit-text-stroke-width: 0.01rem;-webkit-text-stroke-color:black;"> BUK2 on & on </a>
            
                <button class="navbar-toggler" style='opacity:0.5;' type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent"  >
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0" >

                        <li class="nav-item" style='margin-top:0.2rem;'>
                            <a class="nav-link" href='https://www.notion.so/hphk-edu/f63f5d9b2f314af1a081e4ba556db742?v=b42bccc9c40843468e7b53c6ef72e5b4' style="color:white">
                                WhoWeAre
                            </a>
                        </li>

                        <li class="nav-item dropdown" style='margin-top:0.2rem;'>
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:white">
                            Region
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <form action="{% url 'buk2on_on:seoul_main' %}" method = "#">
                                    <input type="submit" value="Seoul"  style="color:gray;" class="dropdown-item">
                                    </form>
                                </li>
                                <li>
                                    <form action="{% url 'buk2on_on:busan_main' %}" method = "#">
                                    <input type="submit" value="Busan"  style="color:gray;" class="dropdown-item">
                                    </form>
                                </li>
                                <li>
                                    <form action="{% url 'buk2on_on:etc_main' %}" method = "#">
                                    <input type="submit" value="etc"  style="color:gray;" class="dropdown-item">
                                    </form>
                                </li>
                            </ul>
                        </li>

                        {% if request.user.is_authenticated%}
                        
                        {% else %}
                            <li class="nav-item dropdown" style='margin-top:0.2rem;'>
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:white">
                                    Account
                                </a>
                                <ul class="dropdown-menu">
                                    {% comment %} <li>
                                        <form action="{% url 'accounts:logout' %}" method = "POST">
                                        {% csrf_token %}
                                        <input type="submit" value="LOGOUT"  style="color:gray;" class="dropdown-item">
                                        </form>
                                    </li> {% endcomment %}
                                    {% comment %} <li>        
                                        <a href="{% url 'accounts:profile' user.username %}" style="color:gray;" class="dropdown-item"> MY ACCOUNT </a>        
                                    </li> {% endcomment %}
                                    <li>
                                        <a href="{% url 'accounts:login' %}" style="color:gray;" class="dropdown-item">LOGIN</a>
                                    </li>
                                    <li>   
                                        <a href="{% url 'accounts:signup' %}" style="color:gray;" class="dropdown-item">CREATE ACCOUNT</a>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>

                    {% comment %} search Bar
                    <div class="input-group d-flex" style="width:20%; margin-right: 20px;">
                        <input type="text" class="form-control" placeholder="search" aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-secondary" type="button" id="button-addon2"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
                    </div>  {% endcomment %}


                    {% if request.user.is_authenticated%}

                        <div class="d-flex" style=" ">
                            {% if request.user.profile_pic %}
                                <a href="{% url 'accounts:profile' user.username %}">
                                    <img src="{{user.profile_pic.url}}" alt="no image"  width="30" height="30" style="border-radius : 70%; overflow:hidden; margin-right:1rem;">
                                </a>
                            {% else %}
                                <a href="{% url 'accounts:profile' user.username %}">
                                    <img src=" {% static 'default_avatar2.jpg' %} " alt="no image"  width="30" height="30" style="border-radius : 70%; overflow:hidden; margin-right:1rem; ">
                                </a>
                            {% endif %}
                        </div>

                    {% endif %}
                    
                    
                {% comment %} <form class="d-flex" role="search"  style='opacity:40%; margin-top:0.2rem;'>
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" >
                    <button  class="btn btn-outline-light"  type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
                    
                </form> {% endcomment %}

                </div>
            </div>
        </nav>
    </div>

  


  <div>
    {% block content %}
    {% endblock content %}
  </div>

  <hr>
  <script src="/static/js/main.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>

<div style= "margin-bottom:3rem"></div>
<footer>Ⓒ C O P Y R I G H T _ J A Y P A K</footer>
</html>