BUK2on_on/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buk2on_on/', include('recommends.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('create_account/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

recommends/urls.py
from django.urls import path
from . import views

app_name = 'buk2on_on'
urlpatterns = [
    path('', views.index , name='index'),
    path('<int:restaurant_pk>/', views.detail , name='detail'),
    path('create/', views.create, name = 'create'),
    path('<int:restaurant_pk>/update/', views.update, name = 'update'),
    path('<int:restaurant_pk>/delete/', views.delete, name = 'delete'),
    path('seoul/', views.seoul_main , name = 'seoul_main'),
    path('busan/', views.busan_main , name = 'busan_main'),
    path('etc/', views.etc_main , name = 'etc_main'),
    path('<int:restaurant_pk>/comments/', views.comments_create , name = 'comments_create'),
] 

recommends/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Restaurant(models.Model):
    province = (('1','Seoul'),('2','Busan'),('3','etc.'))
    region = models.CharField(max_length=20, choices=province)
    name = models.CharField(max_length = 20)
    adress = models.CharField(max_length=50)
    stars = models.IntegerField()
    bestMenu = models.CharField(max_length=100)
    reason = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mainImage = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    

def get_image_filename(instance, filename):
    name = instance.restaurant.name
    slug = slugify(name)
    return "restaurant_images/%s-%s" % (slug, filename)  


class Comment(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Images(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="image")
    image = models.ImageField(blank=False, upload_to=get_image_filename)

    image = ProcessedImageField(
    		blank = True,
            upload_to=get_image_filename,
        	processors = [ResizeToFill(350, 520)],
        	format = 'JPEG',
        	options = {'quality':90},
    		)

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
    def __str__(self):
       return str(self.restaurant)

recommends/forms.py
from django import forms
from .models import *
from django.utils.translation import gettext_lazy as _
from .custom_widgets import PreviewImageFileWidget


class RestaurantForm(forms.ModelForm):

    name = forms.CharField(
    label='Name',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'name',
            'maxlength': 20,
            'size': 40,
            }
        )
    )


    adress = forms.CharField(
        label='Adress',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'adress',
                'maxlength': 50,
                'size': 40,
                }
            ),
        )


    stars = forms.IntegerField(
    label='Stars',
    widget=forms.NumberInput(
        attrs={
            'placeholder': '-',
            'min': 0,
            'max' : 3,
            }
        )
    )

    bestMenu = forms.CharField(
    label='Best Menu',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'Best Menu',
            'maxlength': 100,
            'size': 40,
            }
        )
    )

    reason = forms.CharField(
    label='Comment',
    widget=forms.Textarea(
        attrs={
            'placeholder': 'Reason',
            'maxlength': 200,
            'rows' :4,
            'cols' :42,
            }
        )
    )

    mainImage = forms.ImageField(
    required = True,
    label='Image',
    widget=forms.ClearableFileInput(
        ),
    error_messages={
        'required': '사진을 입력하세요.',
    })

    class Meta:
        model = Restaurant
        exclude = ['user',]


class EditRestaurantForm(forms.ModelForm):

    name = forms.CharField(
    label='Name',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'name',
            'maxlength': 20,
            'size': 40,
            }
        )
    )


    adress = forms.CharField(
        label='Adress',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'adress',
                'maxlength': 50,
                'size': 40,
                }
            ),
        )


    stars = forms.IntegerField(
    label='Stars',
    widget=forms.NumberInput(
        attrs={
            'placeholder': '-',
            'min': 0,
            'max' : 3,
            }
        )
    )

    bestMenu = forms.CharField(
    label='Best Menu',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'Best Menu',
            'maxlength': 100,
            'size': 40,
            }
        )
    )

    reason = forms.CharField(
    label='Comment',
    widget=forms.Textarea(
        attrs={
            'placeholder': 'Reason',
            'maxlength': 200,
            'rows' :4,
            'cols' :42,
            }
        )
    )

    mainImage = forms.ImageField(
    required = True,
    label='Image',
    widget=forms.ClearableFileInput(
        ),
    error_messages={
        'required': '사진을 입력하세요.',
    })

    class Meta:
        model = Restaurant
        exclude = ['user', 'province', 'region', ]


class CommentForm(forms.ModelForm):
    
    content = forms.CharField(
    label='Comment',
    widget=forms.TextInput(
        attrs={
            'placeholder': 'plz share your opinion',
            'maxlength': 100,
            'size': 40,
            }
        )
    )
    class Meta:
        model = Comment
        exclude = ["restaurant",]
 
class ImageForm(forms.ModelForm):

    image = forms.ImageField(
    required = True,
    label='Image',
    widget=forms.ClearableFileInput(attrs={'multiple': True}),
    error_messages={
        'required': '사진을 입력하세요.',
    })

    
    class Meta:
        model = Images
        fields = ('image', )
        labels = {
            'image': _('Image'),
        }
        

recommends/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse




def index(request):
    recommends = Restaurant.objects.all()
    context ={
        'recommends' : recommends,
    }
    return render(request, "recommends/index.html", context)


def seoul_main(request):
    recommends = Restaurant.objects.filter(region = 1)
    images = Images.objects.all()
    context ={
        'recommends' : recommends,
        'images' : images,
    }
    return render(request, "recommends/seoul_main.html", context)



def busan_main(request):
    recommends = Restaurant.objects.filter(region = 2)
    context ={
        'recommends' : recommends,
    }
    return render(request, "recommends/busan_main.html", context)


def etc_main(request):
    recommends = Restaurant.objects.filter(region = 3)
    context ={
        'recommends' : recommends,
    }
    return render(request, "recommends/etc_main.html", context)



def comments_create(request, restaurant_pk ):
    recommend = Restaurant.objects.get(pk=restaurant_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit = False)
        comment.restaurant = recommend
        comment.save()    
    if recommend.region == '1' :
        return redirect('buk2on_on:seoul_main' )
    elif recommend.region == '2' :
        return redirect('buk2on_on:busan_main' )
    elif recommend.region == '3' :
        return redirect('buk2on_on:etc_main' )


def detail(request, restaurant_pk ):
    recommend = Restaurant.objects.get(pk=restaurant_pk)
    comment_form = CommentForm()
    comments = recommend.comments.all()
    context = {
        'recommend' : recommend,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'recommends/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    ImageFormSet = modelformset_factory(Images,form=ImageForm, extra=4)
    
    if request.method == "POST" :
        restaurantform = RestaurantForm(request.POST, request.FILES)
        formset = ImageFormSet(request.POST, request.FILES)
        if restaurantform.is_valid() and formset.is_valid():
            restaurant_form = restaurantform.save(commit=False)
            restaurant_form.user = request.user
            restaurant_form.save()
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    photo = Images(restaurant=restaurant_form, image=image)
                    photo.save()

            if request.POST['region'] == '1' :
                return redirect('buk2on_on:seoul_main' )
            elif request.POST['region'] == '2' :
                return redirect('buk2on_on:busan_main' )
            elif request.POST['region'] == '3' :
                return redirect('buk2on_on:etc_main' )

    else:
        Recommendform = RestaurantForm()
        formset = ImageFormSet(queryset=Images.objects.none())
        context = {
            'Recommendform' : Recommendform,
            'formset' : formset,
        }
    return render(request, 'recommends/create.html', context)


@require_POST
def delete(request, restaurant_pk):
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    restaurant_region = restaurant.region
    restaurant.delete()
    if restaurant_region == '1':
        return redirect('buk2on_on:seoul_main' )
    if restaurant_region == '2':
            return redirect('buk2on_on:busan_main' )
    if restaurant_region == '3':
            return redirect('buk2on_on:etc_main' )


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, restaurant_pk):
    ImageFormSet = modelformset_factory(Images,form=ImageForm, extra=4)

    restaurant = Restaurant.objects.get(pk=restaurant_pk)

    if request.method == 'POST':
        restaurant_form = EditRestaurantForm(request.POST, request.FILES, instance=restaurant)

        if restaurant_form.is_valid()  :
            restaurant_form.save()
            return redirect('buk2on_on:detail', restaurant.pk)
                

        else:
            print(restaurant_form.errors)

    else:
        restaurant_form = EditRestaurantForm(instance=restaurant)
        
    context = {
            'restaurant_form' : restaurant_form,
            'restaurant' : restaurant,
        }
    return render(request, 'recommends/update.html', context)

recommends/templates/recommends/busan_main.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div style="margin:12rem;"></div>

<div class="container">
    <div style="display:flex; flex-direction:row; justify-content:space-between; " >
        <h1 class='section_title'>
            B U S A N 
        </h1>
        <a id="create"   href="{% url 'buk2on_on:create' %}" >+</a>
    </div>


    <div style ="display:flex; flex-direction:column-reverse; flex-wrap:no-wrap;">
        <div class="a_hover" style ="display:flex; gap: 20px 2%; flex:1 1 auto; flex-direction:row; flex-wrap:wrap; justify-content:flex-start; align-itmes:stretch; ">    
            {% for recommend  in recommends %}
            
            <div style="flex-grow:1; margin-bottom:28px;"> 

                <div style= "width: 320px; height520px;">
                    <a href="{% url 'buk2on_on:detail' recommend.pk %}"  style="width: 320px; height : 480px; overflow:hidden; margin:0 auto; background-position: center; background-size:cover;">
                        <img id="detail_feed"  src="{{recommend.mainImage.url}}"  alt="{% static 'main_color.jpg' %}" style= "left:-50%; height:480px; width: 320px;" >
                    </a>
                    <div id="detail_feed_text">
                        <p id="detail_feed_text">{{recommend.name}}
                        {% if recommend.stars == 3 %}
                            <span>★★★</span>
                        {% elif recommend.stars == 2 %}
                            <span>★★</span>
                        {% elif recommend.stars == 1 %}
                            <span>★</span>
                        {% elif recommend.stars == 0 %}
                            <span>none</span>
                        {% endif %} 
                        </p>
                    </div>
                </div>
        
            </div>
            {% endfor %}
        </div>
    </div>
    
</div>
<div style="margin:12rem;"></div>
{% endblock content %}

{% block script %}

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=9bac6e7feb18a7bcee880724d8e51ff4&libraries=services"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };  
    
    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 
    
    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();
    
    
    // 주소로 좌표를 검색합니다
    geocoder.addressSearch('창원시 의창구 중동로 34', function(result, status) {
    
        // 정상적으로 검색이 완료됐으면 
         if (status === kakao.maps.services.Status.OK) {
    
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
    
            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });
    
            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0; background-corlor:black;">hi</div>'
            });
            infowindow.open(map, marker);
    
            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        } 
    });    
    </script>
    
{% endblock script %}

recommends/templates/recommends/create.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div style="margin:12rem;"></div>

<div class="container">
    <h1 class='section_title'>Recommend</h1>

    <form id="post_form" action="{% url 'buk2on_on:create' %}" method="POST"  enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in Recommendform %}
            <div style="margin-bottom: 1.5rem; margin-left: 1rem;">
            {{ field.label_tag }} 
            <div style="margin-top: 0.2rem;">
            {{ field }} <span>{{ field.errors }} </span></div>
            </div>            
        {% endfor %}

        

        {{ formset.management_form }}

        {% for form in formset %}
        
            {% comment %} <div style="margin-bottom: 1.5rem; margin-left: 1rem;">
            {{ form.label_tag }} 
            <div style="margin-top: 0.2rem;">
            {{ form }} <span>{{ form.errors }} </span></div> {% endcomment %}


             <div style="color:red; margin-left: 1rem;">{{ form }} </div> 
            <div>{{form.error_messages}}</div> 
        {% endfor %}

        <div style="margin:8rem;"></div>

        {% comment %} <div id="map" style="width:50%;height:350px;"></div> {% endcomment %}

        <div style="margin:8rem;"></div>
        {% if formset %}
        <input type="submit" value="SUBMIT" style="color:gray;" class="btn btn-outline-secondary">

        {% endif %}
    </form>
    <hr>
</div>
  
{% endblock content %}

{% block script %}

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=9bac6e7feb18a7bcee880724d8e51ff4&libraries=services"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };  
    
    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 
    
    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();
    
    // 주소로 좌표를 검색합니다
    geocoder.addressSearch('창원시 의창구 중동로 34', function(result, status) {
    
        // 정상적으로 검색이 완료됐으면 
         if (status === kakao.maps.services.Status.OK) {
    
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
    
            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });
    
            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0; background-corlor:black;">우리회사</div>'
            });
            infowindow.open(map, marker);
    
            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        } 
    });    
    </script>
    
{% endblock script %}

recommends/templates/recommends/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">


    <div style="margin:12rem;"></div>
    <h1 class="detail_title">{{recommend.name}}</h1>
    <p>
        {% if recommend.user.profile_pic %}
            <a href="{% url 'accounts:profile' recommend.user %}" style="text-decoration: none;">
                <img src="{{recommend.user.profile_pic.url}}" alt="no image"  width="30" height="30" style="text-decoration: none; border-radius : 70%; overflow:hidden; margin-right:1rem;">
                <span style="text-decoration: none; color:gray;">{{recommend.user|upper}}</span>
            </a>
        {% else %}
            <a href="{% url 'accounts:profile' recommend.user %}" style="text-decoration: none;">
                <img src=" {% static 'default_avatar2.jpg' %} " alt="no image"  width="30" height="30" style="text-decoration: none; border-radius : 70%; overflow:hidden; margin-right:1rem; ">
                <span style="text-decoration: none; color:gray;">{{recommend.user|upper}}</span>
            </a>
        {% endif %}
    </p>
    <hr>
    <div style= "margin-bottom:2rem"></div>


      
    <div style="display: flex; flex-direction:row">
        <div style="width: 30%;">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner" style="border:1px solid black; background-color:greenyellow; width:320px; height: 480px;">
                    <div class="carousel-item active">
                        <img src="{{recommend.mainImage.url}}" class="d-block" style="left:10px; width:350px; height: 520px; overflow:hidden" alt="...">
                      </div>
                      {% for img in recommend.image.all %}
                            <div class="carousel-item" style="width:350px; height: 520px; overflow:hidden ">
                                <img src="{{img.image.url}}"  class="d-block" style="max-width:initial " alt="..." >
                            </div>
                        {% endfor %}
                    
    
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div> 
        </div>

        <br>
        <div style="margin-left:3rem;">
            <form action="{% url 'buk2on_on:comments_create' recommend.pk %}" method="POST">
                {% csrf_token %}
                {{comment_form}}
                <input type="submit" value="share">
            </form>
            <ul style="margin-top:2rem">
                {% for comment in comments  %}
                    <li style="margin-top:1rem;">{{comment.content}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <br>


    {% if user == recommend.user %}
        <hr>
        <form action= "{% url 'buk2on_on:update' recommend.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-secondary" value="EDIT">
        </form>  
        <hr>
            <form action= "{% url 'buk2on_on:delete' recommend.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="DELETE" class="btn btn-danger">
            </form>
        <hr>
    {% endif %}

</div>

{% endblock content %}

recommends/templates/recommends/seoul_main.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div style="margin:12rem;"></div>

<div class="container">
    <div style="display:flex; flex-direction:row; justify-content:space-between; " >
        <h1 class='section_title'>
            S E O U L 
        </h1>
        <a id="create"   href="{% url 'buk2on_on:create' %}" >+</a>
    </div>


    <div style ="display:flex; flex-direction:column-reverse; flex-wrap:no-wrap;">
        <div class="a_hover" style ="display:flex; gap: 20px 2%; flex:1 1 auto; flex-direction:row; flex-wrap:wrap; justify-content:flex-start; align-itmes:stretch; ">    
            {% for recommend  in recommends %}
            
            <div style="flex-grow:1; margin-bottom:28px;"> 

                {% comment %} 모달 {% endcomment %}
                {% comment %} <div id="modal_detail_feed" class="modal_overlay">
                    <div class="modal_window">
                        <div class="modal_title">
                            <div class="modal_title_side"></div>
                            <h3 style="font-family: Gowun Batang; font-weight:bold;"> {{recommend.name}} </h3>
                            <div class="modal_title_side">
                                <span id="close_modal" class="material-icons-outlined">
                                    <div > 
                                        <span class="close">&times;</span>  
                                    </div>
                                </span>
                            </div>
                        </div>
                        <div class="modal_image" style="display: flex; flex-direction:row" >
                            <div>
                                <div style="overflow:hidden; margin:0 auto; background-position: center; background-size:cover; width : 350px;">
                                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                                        <div class="carousel-inner">
                                          <div class="carousel-item active">
                                            <img src="{{recommend.mainImage.url}}" class="d-block" style="left:10px; width:350px; height: 520px " alt="...">
                                          </div>
                                          {% for img in recommend.image.all %}
                                            <div class="carousel-item">
                                                <img src="{{img.image.url}}"  class="d-block" style="left:10px; width:350px; height: 520px " alt="..." >
                                            </div>
                                            {% endfor %}
                                        </div>
                                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                          <span class="visually-hidden">Previous</span>
                                        </button>
                                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                          <span class="visually-hidden">Next</span>
                                        </button>
                                      </div>
                                </div>
                            </div>
                            <div style="display: flex; flex-direction:column;  align-items: flex-start; text-align : left; margin-left:20px; margin-right:20px;">
                                <div style="margin:1rem;"></div>
                                {% if recommend.user.profile_pic %}
                                    <a href="{% url 'accounts:profile' recommend.user %}">
                                        {% if recommend.user.profile_pic %}
                                        <img src="{{recommend.user.profile_pic.url}}" alt="no image"  width="45" height="45" style="border-radius : 70%; overflow:hidden; margin-right:1rem;">
                                        <span style=" text-decoration:none; color:gray; font-size:2rem; height:50%;">{{recommend.user}}</span>
                                        {% else %}
                                        <img src="{% static 'default_avatar2.jpg' %}" alt="no image"  width="45" height="45" style="border-radius : 70%; overflow:hidden; margin-right:1rem;">
                                        <span style=" text-decoration:none; color:gray; font-size:2rem; height:50%;">{{recommend.user}}</span>
                                        {% endif %}
                                    </a>
                                {% else %}
                                    <a href="{% url 'accounts:profile' recommend.user %}" style="text-decoration:none; display:flex; flex-direction : row; align-items : center;" >
                                        <img src=" {% static 'default_avatar2.jpg' %} " alt="no image"  width="45" height="45" style="border-radius : 70%; overflow:hidden; margin-right:1rem; ">
                                        <span class="detail_modal_recommend_user"  >{{recommend.user|upper}}</span>
                                    </a>
                                {% endif %}
                                <div style="margin:2rem;"></div>
                                {% if recommend.stars == 3 %}
                                    <p style = "margin-bottom:2rem;">★★★</p>
                                {% elif recommend.stars == 2 %}
                                    <p>★★</p>
                                {% elif recommend.stars == 1 %}
                                    <p>★</p>
                                {% elif recommend.stars == 0 %}
                                    <p>none</p>
                                {% endif %} 
                                <p class="detail_modal_text">{{recommend.adress}}</p>
                                <p class="detail_modal_text">{{recommend.bestMenu}}</p>
                                <p class="detail_modal_text">{{recommend.reason}}</p>
                                <div id="map" style="width:400px;height:100%;"></div>

                                {% comment %} <p class="detail_modal_text">{{recommend.comments}}</p> {% endcomment %}
                            {% comment %} </div>
                        </div>
                    </div>
                </div>  {% endcomment %}

                {% comment %} 대문카드 {% endcomment %}
                <div style= "width: 320px; height520px;">
                    <a href="{% url 'buk2on_on:detail' recommend.pk %}"  style="width: 320px; height : 480px; overflow:hidden; margin:0 auto; background-position: center; background-size:cover;">
                        <img id="detail_feed"  src="{{recommend.mainImage.url}}"  alt="{% static 'main_color.jpg' %}" style= "left:-50%; height:480px; width: 320px;" >
                    </a>
                    <div id="detail_feed_text">
                        <p id="detail_feed_text">{{recommend.name}}
                        {% if recommend.stars == 3 %}
                            <span>★★★</span>
                        {% elif recommend.stars == 2 %}
                            <span>★★</span>
                        {% elif recommend.stars == 1 %}
                            <span>★</span>
                        {% elif recommend.stars == 0 %}
                            <span>none</span>
                        {% endif %} 
                        </p>
                    </div>
                </div>
        
            </div>
            {% endfor %}
        </div>
    </div>
    
</div>
<div style="margin:12rem;"></div>
{% endblock content %}

{% block script %}

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=9bac6e7feb18a7bcee880724d8e51ff4&libraries=services"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };  
    
    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 
    
    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();
    
    
    // 주소로 좌표를 검색합니다
    geocoder.addressSearch('창원시 의창구 중동로 34', function(result, status) {
    
        // 정상적으로 검색이 완료됐으면 
         if (status === kakao.maps.services.Status.OK) {
    
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
    
            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });
    
            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0; background-corlor:black;">hi</div>'
            });
            infowindow.open(map, marker);
    
            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        } 
    });    
    </script>
    
{% endblock script %}